#!/bin/bash


URL="https://pokeapi.co/api/v2/pokemon/pikachu"

OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

curl -s -o "$OUTPUT_FILE" -w "%{http_code}" "$URL" > status_code.txt

STATUS_CODE=$(cat status_code.txt)
rm status_code.txt


if [ "$STATUS_CODE" -ne 200 ]; then
    echo "Request failed with status code: $STATUS_CODE" >> "$ERROR_FILE"
    rm -f "$OUTPUT_FILE" # Remove partial file if request failed
fi
